/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User_Online;

import java.awt.*;
import java.io.IOException;

/**
 *
 * @author hp
 */
public class Approval extends javax.swing.JPanel {
    Approvals_Request appr;
    public static Approvals_Request global_appr = new Approvals_Request();
    /**
     *
     * Creates new form Approval
     */

    public Approval(Approvals_Request ac) {
        appr = ac;
        initComponents();
        gradient2.col2 = new Color(248,248,248);
        gradient2.col1 = new Color(252,252,252);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        gradient2 = new resources.swing.Gradient();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button1 = new resources.swing.Button();
        button2 = new resources.swing.Button();

        setOpaque(false);

        gradient2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Amount");
        gradient2.add(jLabel4);
        jLabel4.setBounds(10, 40, 220, 20);

        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(appr.cash+".RS");
        gradient2.add(jLabel5);
        jLabel5.setBounds(10, 60, 220, 40);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(appr.name_from);
        gradient2.add(jLabel2);
        jLabel2.setBounds(10, 0, 220, 25);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(appr.ac_num_from);
        gradient2.add(jLabel3);
        jLabel3.setBounds(10, 20, 220, 25);

        button1.setBackground(new java.awt.Color(255, 129, 114));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("REJECT");
        button1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    button1ActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        button2.setBackground(new java.awt.Color(30, 156, 232));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("SEND");
        button2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    button2ActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(gradient2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(gradient2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        User_Background.showForm(new Confirm_send(appr.ac_num_from,appr.cash));
        global_appr.remove(this.appr);
        global_appr.add_to_file();
//        Approvals_Request ac = new Approvals_Request(User_Background.auth_enter.getacc(),ac_n,User_Background.global_online.get_name(ac_n),User_Background.auth_enter.name_acc(),cash,0);
//        appr.add_appr(ac);
//        this.appr = ac;
    }

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        global_appr.remove(this.appr);
        global_appr.add_to_file();
        User_Background.showForm(new Send_mone(new UserAcount(User_Background.auth_enter),User_Background.auth_enter));
    }

    // Variables declaration - do not modify
    private resources.swing.Button button1;
    private resources.swing.Button button2;
    private resources.swing.Gradient gradient2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration
}
