/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User_Online;

import myon.bank.pack.Accounts;
import myon.bank.pack.Email_Send;
import myon.bank.pack.OnlineUsers;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author hp
 */
public class Change_passWord extends javax.swing.JPanel {

    /**
     * Creates new form Change_passWord
     */
    Image img21;
    int showing_pass = 0;
    static Accounts global_account = new Accounts();
    OnlineUsers ou = new OnlineUsers();
    Email_Send nes = new Email_Send();
    Accounts ac;
    String accc;
    public Change_passWord(String acc) throws IOException, ClassNotFoundException {
        accc = acc;
        global_account.file_to_arraylist();
        ac= global_account.get_acc(acc);
        boolean stat = ou.send_opt(ac);
        BufferedImage img2 = ImageIO.read(new File(Const.basePath + "rc\\resources\\icon\\bank.png"));
        img21 = img2.getScaledInstance(200,160,BufferedImage.SCALE_SMOOTH);
        initComponents();

        gradient1.col1 = new Color(255,255,255);
        gradient1.col2 = new Color(249,245,249);
        gradient1.round = 35;
        myTextField1.col1 = new Color(230, 245, 241);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setOpaque(false);
        gradient1 = new resources.swing.Gradient();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        myTextField1 = new resources.swing.MyTextField();
        button1 = new resources.swing.Button();
        buttonMenu2 = new resources.swing.ButtonMenu();
        myPasswordField1 = new resources.swing.MyPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        gradient1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(img21));
        gradient1.add(jLabel2);
        jLabel2.setBounds(40, 40, 200, 160);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 123, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reset Password");
        gradient1.add(jLabel1);
        jLabel1.setBounds(52, 0, 164, 18);

        myTextField1.setBackground(new java.awt.Color(230, 245, 241));
        myTextField1.setForeground(new java.awt.Color(51, 51, 51));
        myTextField1.setHint("OTP, "+nes.acc_hash(ac.email_acc()));
        gradient1.add(myTextField1);
        myTextField1.setBounds(10, 230, 260, 38);

        button1.setBackground(new java.awt.Color(255, 129, 114));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("LOGIN");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    button1ActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        gradient1.add(button1);
        button1.setBounds(80, 340, 120, 30);

        buttonMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/icons8-closed-eye-15.png"))); // NOI18N
        buttonMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenu2ActionPerformed(evt);
            }
        });
        gradient1.add(buttonMenu2);
        buttonMenu2.setBounds(240, 290, 20, 18);

        myPasswordField1.setBackground(new java.awt.Color(230, 245, 241));
        myPasswordField1.setForeground(new java.awt.Color(51, 51, 51));
        myPasswordField1.setHint("New Password");
        gradient1.add(myPasswordField1);
        myPasswordField1.setBounds(10, 280, 260, 38);

        jLabel3.setForeground(new java.awt.Color(1, 227, 189));
        jLabel3.setText("this service.");
        gradient1.add(jLabel3);
        jLabel3.setBounds(10, 510, 260, 30);

        jLabel4.setForeground(new java.awt.Color(1, 227, 189));
        jLabel4.setText("You must have an account in the bank to avail");
        gradient1.add(jLabel4);
        jLabel4.setBounds(10, 500, 260, 16);

        add(gradient1);
        gradient1.setBounds(0, 0, 280, 543);
    }// </editor-fold>

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException, ClassNotFoundException {
        if(ou.enter_otp(myTextField1.getText())){
            char[] password = myPasswordField1.getPassword();
            ou.change_without_online(ac,new String(password));
            ou.add_to_file();
            User_Background.create(accc, new String(password));
        }

    }

    private void buttonMenu2ActionPerformed(java.awt.event.ActionEvent evt) {
        if(showing_pass==0){
            myPasswordField1.setEchoChar((char)0);
            showing_pass = 1;
            buttonMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/icons8-eye-15.png"))); // NOI18N
        }
        else{
            myPasswordField1.setEchoChar('*');
            showing_pass = 0;
            buttonMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/icons8-closed-eye-15.png"))); // NOI18N
        }
    }


    // Variables declaration - do not modify
    private resources.swing.Button button1;
    private resources.swing.ButtonMenu buttonMenu2;
    private resources.swing.Gradient gradient1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private resources.swing.MyPasswordField myPasswordField1;
    private resources.swing.MyTextField myTextField1;
    // End of variables declaration
}
