/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User_Online;

import javax.swing.*;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

import static User_Online.Bill_Payment.billHistory;

/**
 *
 * @author hp
 */
public class Confirm_Pay extends javax.swing.JPanel {

    /**
     * Creates new form Confirm_send
     */
    String name;
    String ref;String bill;
    String last_date;
    String late_bill;

    public Confirm_Pay(String name,String ref,String bill,String last_date,String late_bill) {
        this.name = name;
        this.ref = ref;
        this.bill = bill;
        this.last_date = last_date;
        this.late_bill = late_bill;

//        try {
////            billHistory.fileToArrayList(); // Load history from file
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        int index = name.indexOf("/");
        System.out.println(index);
        // If "/" is found, take the substring before it
        if (index != -1) {
            this.name = name.substring(0, index-1);  // Trims the name up to the first "/"
        }else {
            index = name.indexOf("-");
            this.name = name.substring(0, index-1);
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yy");  // Format to match "12 Dec 24"
        try {
            Date dueDate = sdf.parse(last_date);  // Convert due date string to Date object
            Date currentDate = new Date();  // Get today's date

            // Compare the due date with today's date
            if (currentDate.after(dueDate)) {
                // If today's date is after the due date, set the late bill
                this.bill = late_bill;
            }

            // Display the due date or after due date based on the comparison

        } catch (Exception e) {
            e.printStackTrace();
        }



    initComponents();
        roundPanel1.round = 35;
        gradient1.col1 = new Color(247,248,248);
        gradient1.col2 = new Color(252,252,252);
        gradient2.col2 = new Color(248,248,248);
        gradient2.col1 = new Color(252,252,252);
        gradient3.col1 = new Color(255,129,114);
        gradient3.col2 = new Color(249,123,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        roundPanel1 = new resources.swing.RoundPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonMenu1 = new resources.swing.ButtonMenu();
        gradient1 = new resources.swing.Gradient();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gradient2 = new resources.swing.Gradient();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gradient3 = new resources.swing.Gradient();
        buttonMenu2 = new resources.swing.ButtonMenu();

        setOpaque(false);
        setLayout(null);

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 123, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bill");
        roundPanel1.add(jLabel1);
        jLabel1.setBounds(54, 9, 164, 18);

        buttonMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/icons8-back-15.png"))); // NOI18N
        buttonMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenu1ActionPerformed(evt);
            }
        });
        roundPanel1.add(buttonMenu1);
        buttonMenu1.setBounds(6, 9, 20, 18);

        gradient1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(name);
        gradient1.add(jLabel2);
        jLabel2.setBounds(6, 6, 256, 25);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(ref);
        gradient1.add(jLabel3);
        jLabel3.setBounds(6, 31, 256, 25);

        roundPanel1.add(gradient1);
        gradient1.setBounds(8, 40, 270, 60);

        gradient2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(late_bill+".RS");
        gradient2.add(jLabel4);
        jLabel4.setBounds(140, 80, 120, 25);

        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(bill+".RS");
        gradient2.add(jLabel5);
        jLabel5.setBounds(10, 30, 250, 50);

        jLabel6.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bill");
        gradient2.add(jLabel6);
        jLabel6.setBounds(6, 6, 256, 25);

        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("After Due :");
        gradient2.add(jLabel7);
        jLabel7.setBounds(10, 80, 120, 25);

        jLabel8.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Due Date :");
        gradient2.add(jLabel8);
        jLabel8.setBounds(10, 110, 120, 25);

        jLabel9.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(last_date);
        gradient2.add(jLabel9);
        jLabel9.setBounds(140, 110, 120, 25);

        roundPanel1.add(gradient2);
        gradient2.setBounds(10, 110, 270, 140);

        gradient3.setLayout(null);

        buttonMenu2.setText("PAY "+bill);
        buttonMenu2.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
        buttonMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenu2ActionPerformed(evt);
            }
        });
        gradient3.add(buttonMenu2);
        buttonMenu2.setBounds(6, 6, 196, 37);

        roundPanel1.add(gradient3);
        gradient3.setBounds(40, 270, 210, 50);

        add(roundPanel1);
        roundPanel1.setBounds(0, 0, 280, 540);
    }// </editor-fold>

    private void buttonMenu1ActionPerformed(java.awt.event.ActionEvent evt) {
        User_Background.showForm(new UserAcount(User_Background.auth_enter));
    }

    private void buttonMenu2ActionPerformed(java.awt.event.ActionEvent evt) {
        Bill_History bill = billHistory.returnBill(ref);
        if (bill != null) {
            bill.isPaid = true;  // Mark the bill as paid
            try {
                boolean a = Send_mone.gou.send(User_Background.auth_enter,"PK-9140-5878-1212-1348", Float.parseFloat(this.bill),"Electricity Bill");
                if(a) {
                    billHistory.addToFile(); // Save the updated history to file
                    JOptionPane.showMessageDialog(this, "Bill paid successfully!", "Payment Confirmed", JOptionPane.INFORMATION_MESSAGE);
                    // Optionally, navigate to another screen, e.g., the user's account

                }else {
                    JOptionPane.showMessageDialog(this, "Low Balance...", "Error", JOptionPane.ERROR_MESSAGE);
                }
                User_Background.showForm(new UserAcount(User_Background.auth_enter));
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error saving payment history. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bill not found in history.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify
    private resources.swing.ButtonMenu buttonMenu1;
    private resources.swing.ButtonMenu buttonMenu2;
    private resources.swing.Gradient gradient1;
    private resources.swing.Gradient gradient2;
    private resources.swing.Gradient gradient3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private resources.swing.RoundPanel roundPanel1;
    // End of variables declaration
}
